### ISSUE TITLE
Content type "boolean" (More related to event store design)

### ISSUE THREAD

**Issue by michael-schnell** [jen20/EventStore.Java#5]
This issue is more related to the design of the event store itself, but maybe it's a good place to discuss this from the perspective of an event store user. I [discussed](https://groups.google.com/forum/#!searchin/event-store/content$20type/event-store/ID3_ksintKE/HSQVJA8L6I4J) this already with Greg, but I still don't fully understand why the content type is an "int" (in this case a boolean) and there is no content type for the meta data:

``` java
public class EventData {
    private final UUID eventId;
    private final String type;
    private final Boolean isJson;
    private final byte[] data;
    private final byte[] metadata;
}
```

The better design woulkd be like this:

``` java
public class EventData {
    private final UUID eventId;
    private final String type;
    private final String dataContentType;
    private final byte[] data;
    private final String metaContentType;
    private final byte[] meta;
}
```

This way the user has full control over the bytes from data and meta content. To be backward compatible the current "isJson" can easily be mapped to something like `dataContentType.contains("application/json")`.

When the user wants to to deserialize the data for example, he can choose the appropriate deserializer by using the information from the dataContentType or metaContentType. 

Of course I can put all this stuff into the meta data, but then I need to assume a fixed format (JSON, XML) for the meta content. I think having a "content-type" (mime-type) string that describes what is inside the byte array feels much more natural for both data blocks (data & meta).

**Comment by jen20** [comment]
We need to read metadata, so it must he json. Originally data type was a
bool (json vs not) but we could support other formats in projection (eg
bson) so it's now an int enumeration.

## 

James

**Comment by michael-schnell** [comment]
Reading meta data should not be a problem:
a) It's empty => No need to read it
b) It's "application/json" => Process it
c) It's something else => Don't read it (Same as "empty")
This would also more easily allow enhancing the processing: Process if "application/xml" for example.

**Comment by jen20** [comment]
We can't quite make it that simple - we absolutely must have the ability to parse and add to the metadata in all cases (things like soft stream deletion use it, as well as projection output correlation/causation tracking).

This is mostly an artefact of the original transaction file design though. It's possible that when we come to re-examine that (likely for a V4) this might become something we'll consider.

**Comment by michael-schnell** [comment]
OK, i added a [feature request](https://github.com/EventStore/EventStore/issues/493) for this.
