### ISSUE TITLE
Splitting the interface into three parts?

### ISSUE THREAD

**Issue by michael-schnell** [jen20/EventStore.Java#6]
How about splitting the interfaces into four parts:

1) ReadOnlyEventStoreConnection 
2) WritableEventStoreConnection
3) SubscribableEventStoreConnection
4) EventStoreConnection extends (1), (2), (3)

This would allow the user to select for example if he only wants to read and does not require other functionality.

```
@Inject
private ReadOnlyEventStoreConnection es;
```

This makes it very clear, that in this case it's not wanted or allowed to write.

A nice side effect is that the interfaces are smaller if we have methods with different arguments (`Collection<EventData>` vs. `EventData... events`).

**Comment by jen20** [comment]
This seems reasonable.

**Comment by jen20** [comment]
I ended up using `ReadableEventStore` in preference to `ReadOnlyEventStore` for consistency. It might be desirable at some point to have a separate `ReadOnlyEventStore` interface composing `ReadableEventStoreConnection` and `WriteableEventStoreConnection` with `AutoCloseable`.
