### ISSUE TITLE
Rename "EventStoreConnection" to "EventStore" and "connect" to "open"

### ISSUE THREAD

**Issue by michael-schnell** [jen20/EventStore.Java#7]
Instead of

``` java
public interface EventStoreConnection {
    CompletableFuture connect();
    void close();
}
```

it should be

``` java
public interface EventStore {
    CompletableFuture open();
    void close();
}
```

**Comment by jen20** [comment]
Not convinced on this one - I prefer making it clear through the interface name that this is indeed a connection from which you should expect latency, not a local operation. Admittedly you _could_ implement the interface with local storage, but that seems like an application level concern. However, we may want to consider implementing `AutoClosable` here.

**Comment by michael-schnell** [comment]
OK, can live with both :+1:
