### ISSUE TITLE
Add credentials

### ISSUE THREAD

**Issue by michael-schnell** [jen20/EventStore.Java#8]
Credentials should be added:

For the open/connect method: These are the default credentials to use if no credentials are passed with a method call.

``` java
CompletableFuture open(Credentials credentials);
```

Variant A): For all method calls there are two versions: One with and one without credentials

``` java
CompletableFuture<WriteResult> appendToStream(Credentials credentials, String streamName, int expectedVersion, EventData... events);
CompletableFuture<WriteResult> appendToStream(String streamName, int expectedVersion, EventData... events);
```

Variant B): Add an Optional to all methods:

``` java
CompletableFuture<WriteResult> appendToStream(Optional<Credentials> credentials, String streamName, int expectedVersion, EventData... events);
```

Variant C): Have only one method, but allow null for credentials:

``` java
CompletableFuture<WriteResult> appendToStream(@Nullable Credentials credentials, @NotNull String streamName, int expectedVersion, @NotNull EventData... events);
```

I personally prefer the "Optional" variant.

**Comment by jen20** [comment]
I've gone with variant A - it's ugly but doesn't mean passing in extraneous parameters if you specify default credentials (which is a common case still). Passing in the credentials should be a responsibility of the builder (to follow) rather than on the `Connect` method in my opinion.
